using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using CVDRiskScores.Enums;
using CVDRiskScores.Models.SCORE2;
using CVDRiskScores.Resources.Languages;
using CVDRiskScores.Services.Navigation;
using CVDRiskScores.Services.Popup;
using CVDRiskScores.Services.SCORE2;

namespace CVDRiskScores.MVVM.ViewModels.SCORE2
{
    public partial class Score2ViewModel : ObservableObject
    {
        // underlying model (kept for service calls and result)
        [ObservableProperty]
        private Score2Model score2 = new Score2Model();

        // VM properties for binding (use Toolkit generator)
        [ObservableProperty]
        private int age;

        [ObservableProperty]
        private int systolicBloodPressure;

        [ObservableProperty]
        private int totalCholesterol;

        [ObservableProperty]
        private int hdlCholesterol;

        [ObservableProperty]
        private bool isSmoker;

        // already used: int index mapping to enum (0=Male,1=Female)
        [ObservableProperty]
        private int genderIndex = 0;

        [ObservableProperty]
        private string validationError;

        private readonly ISCORE2_Service score2Service;
        private readonly IScore2NavigationStore navStore;
        private readonly IUIPopupService _popupService;

        public Score2ViewModel(ISCORE2_Service service, IScore2NavigationStore navigationStore, IUIPopupService popupService)
        {
            score2Service = service;
            navStore = navigationStore;
            _popupService = popupService;

            // initialize VM props from model defaults
            SyncFromModel();
        }

        // synchronize VM properties from Score2 model
        void SyncFromModel()
        {
            if (Score2 == null) Score2 = new Score2Model();
            Age = Score2.Age ?? 0;
            SystolicBloodPressure = Score2.SystolicBloodPressure ?? 0;
            TotalCholesterol = Score2.TotalCholesterol ?? 0;
            HdlCholesterol = Score2.HDLCholesterol ?? 0;
            IsSmoker = Score2.IsSmoker;
            GenderIndex = (int)Score2.Gender;
        }

        // called when user changes the picker (generated by [ObservableProperty])
        partial void OnGenderIndexChanged(int value)
        {
            if (Enum.IsDefined(typeof(Genero), value))
            {
                var newGender = (Genero)value;
                if (Score2 == null) return;
                if (Score2.Gender != newGender)
                    Score2.Gender = newGender;
            }
        }

        // called when Score2 property is replaced
        partial void OnScore2Changed(Score2Model value)
        {
            if (value == null) return;

            // propagate to VM properties only when changed to avoid unnecessary notifications
            var newAge = value.Age ?? 0;
            if (Age != newAge) Age = newAge;

            var newSbp = value.SystolicBloodPressure ?? 0;
            if (SystolicBloodPressure != newSbp) SystolicBloodPressure = newSbp;

            var newTotal = value.TotalCholesterol ?? 0;
            if (TotalCholesterol != newTotal) TotalCholesterol = newTotal;

            var newHdl = value.HDLCholesterol ?? 0;
            if (HdlCholesterol != newHdl) HdlCholesterol = newHdl;

            if (IsSmoker != value.IsSmoker) IsSmoker = value.IsSmoker;

            var idx = Enum.IsDefined(typeof(Genero), value.Gender) ? (int)value.Gender : 0;
            if (GenderIndex != idx) GenderIndex = idx;

            // synchronize validation message (so UI label binds to VM property)
            ValidationError = value.ValidationError;
        }
        [RelayCommand]
        public async Task Calculate()
        {
            // copy VM values into model before calculation
            Score2.Age = Age;
            Score2.SystolicBloodPressure = SystolicBloodPressure;
            Score2.TotalCholesterol = TotalCholesterol;
            Score2.HDLCholesterol = HdlCholesterol;
            Score2.IsSmoker = IsSmoker;
            Score2.Gender = Enum.IsDefined(typeof(Genero), GenderIndex) ? (Genero)GenderIndex : Genero.Male;

            // call service
            Score2 = score2Service.ValidateAndCalculate(Score2);

            // ensure VM reflects possibly adjusted/validated values returned
            Age = Score2.Age ?? Age;
            SystolicBloodPressure = Score2.SystolicBloodPressure ?? SystolicBloodPressure;
            TotalCholesterol = Score2.TotalCholesterol ?? TotalCholesterol;
            HdlCholesterol = Score2.HDLCholesterol ?? HdlCholesterol;
            IsSmoker = Score2.IsSmoker;
            GenderIndex = (int)Score2.Gender;

            ValidationError = Score2.ValidationError;

            if (!string.IsNullOrEmpty(Score2.ValidationError))
            {
                await Shell.Current.DisplayAlert(AppResources.TituloErroValidacao, Score2.ValidationError, "Ok");
                return;
            }

            navStore.LastResult = Score2;

            if (Score2 != null)
            {
                var badge = Score2.RiskScore.ToString("F1");
                var subtitle = Score2.ClinicalAdvice ?? string.Empty;
                await _popupService.ShowSimulationResultAsync(Score2, title: "SCORE2", subtitle: subtitle, badge: $"{badge}%");
            }
        }

        [RelayCommand]
        public async Task GoBack() => await Shell.Current.GoToAsync("..");

        [RelayCommand]
        public async Task NewSimulation()
        {
            Score2 = new Score2Model();
            // Sync VM props from fresh model
            SyncFromModel();
            await Shell.Current.GoToAsync($"//Score2RiskScorePage");
        }
    }
}